# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170725_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visualizacoes',
            field=models.IntegerField(default=0),
        ),
    ]
